pinpoint-hbase:
  container_name: pinpoint-hbase
  hostname: hbase
  image: registry.saas.hand-china.com/tools/pinpoint-hbase-alone
  restart: always
  expose:
    - "2181"
    - "16010"
  ports:
    - "2181:2181"
    - "16010:16010"
  volumes:
    - /u999/hapm/hbase:/home/pinpoint/hbase
    - /u999/hapm/zookeeper:/home/pinpoint/zookeeper

pinpoint-collector:
  container_name: pinpoint-collector
  hostname: collector
  image: registry.saas.hand-china.com/tools/pinpoint-collector-alone
  restart: always
  expose:
    - "9994"
    - "9995"
    - "9996"
  ports:
    - "9994:9994"
    - "9995:9995/tcp"
    - "9996:9996/tcp"
    - "9995:9995/udp"
    - "9996:9996/udp"
  environment:
    HBASE_HOST: hbase
    HBASE_PORT: 2181
    COLLECTOR_TCP_PORT: 9994
    COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
    COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
    CLUSTER_ENABLE: 'false'
    DISABLE_DEBUG: 'true'
  links:
    - pinpoint-hbase:hbase

pinpoint-web:
  container_name: pinpoint-web
  hostname: web
  image: registry.saas.hand-china.com/tools/pinpoint-web-alone
  restart: always
  expose:
    - "8080"
  ports:
    - "18080:8080"
  environment:
    HBASE_HOST: hbase
    HBASE_PORT: 2181
    CLUSTER_ENABLE: 'false'
    ADMIN_PASSWORD: admin123
    DISABLE_DEBUG: 'true'
  links:
    - pinpoint-hbase:hbase
